---
title: "OpenHDF5"
author: "Amy Hudson"
date: "June 20, 2016"
output: html_document
---

## About this code

```{r load-libraries }

# load libraries
library(raster)
library(rhdf5)
library(rgdal)

```

## Let's open a file

```{r select-file}

f<- "../NEONdata/D17-California/TEAK/2013/spectrometer/reflectance/Subset3NIS1_20130614_100459_atmcor.h5"
#tabs are our friends

#view h5 structure

h5ls(f)

```


## Import Spatial Information
Spatial information

```{r import-spatial-info}

#import spatial info (option dash)
mapInfo <- h5read(f,
                  "map info",
                  read.attributes = T)
mapInfo
```

## Grab Reflectance Metadata

```{r get-refl-metadata}

#read in reflectance data attributes
reflInfo <- h5readAttributes(file = f,
                             name = "Reflectance")
reflInfo
# define scale factor
scaleFactor <- reflInfo$`Scale Factor`
str(scaleFactor)

# define no data value
noDataValue <- as.numeric(reflInfo$`data ignore value`)
str(noDataValue)
```

## Import Data Dims

```{r import-dims}

#open file for viewing
fid <- H5Fopen(f)
str(fid)
#open the reflectance dataset
did <- H5Dopen(fid,"Reflectance")
did
# r is reading in things differently... sees 544 as rows...

#grab the dataset dimensions

sid <- H5Dget_space(did)
dims <- H5Sget_simple_extent_dims(sid)$size
str(dims)

#close all open connections
H5Sclose(sid)
H5Dclose(did)
H5Fclose(fid)
```

## Read IN Reflectance Data
Notes!

```{r read-data}
#extract slice of H5 file
b56 <- h5read(f,
              "Reflectance",
              index = list(1:dims[1],1:dims[2],56))
b56
class(b56)
```

## Convert Data to Matrix

```{r convert-matrix}
#convert to matrix
b56 <- b56[,,1]

#let's plot some data FINALLY
image(b56)
image(log(b56), main = "Band 56 with log Transformation")
hist(b56)
```

## Time to clean up our data

```{r data-clean-up}

#assign no data values to object
b56[b56 == noDataValue] <- NA

#apply scale factor
b56 <- b56/ scaleFactor
hist(b56)

```

## Transpose Data

```{r transpose-data}
b56 <- t(b56)
image(log(b56))
```

## Create Spatial Extent

```{r create-spatial-extent}
#split out Map Info object
mapInfo <- strsplit(mapInfo,",")
mapInfo <- unlist(mapInfo)
mapInfo

#value at element 3 in list
mapInfo[3]

#define upper left hand corner coordinate
xMin <- as.numeric(mapInfo[4])
yMax <- as.numeric(mapInfo[5])

#get spatial resolution
xres <- as.numeric(mapInfo[6])
yres <- as.numeric(mapInfo[7])

#Calculate Xmax and Ymin
xMax <- xMin + (dims[1] * xres) 
yMin <- yMax - (dims[2] * yres) 
```


## Create spatial extent

```{r create-extent}

#create extent object
rasExt <- extent(xMin,xMax,
                yMin,yMax)
rasExt

#create raster object
b56r <- raster(b56,
               crs=CRS("+init=epsg:32611"))

extent(b56r) <- rasExt
b56r

plot(b56r, main = "spatially referenced data")
```

# Import NEON Functions

```{r import-using-functions}
#install devtools
#install.packages("devtools")
library(devtools)

#install_github("lwasser/neon-aop-package/neonAOP")
library(neonAOP)
b55 <- open_band(f,
                 bandNum = 55,
                 epsg = 32611)
b55
plot(b55)

#define code
epsg<- 32611

#import several bands
bands<- c(58,34,19)

#create raster stack
RGBStack <- create_stack(f,
                         bands = bands,
                         epsg = epsg)
RGBStack

#plot RGB image
plotRGB(RGBStack,
        stretch = 'lin')

bands<- c(90,34,19)
CIRStack<- create_stack(f,
                         bands = bands,
                         epsg = epsg)
plotRGB(CIRStack,stretch='lin')
```



